### ISSUE TITLE
Do you have downloaded dataset because my ip

### ISSUE THREAD

**Issue by MLrookie** [VoxBlink2/ScriptsForVoxBlink2#7]
My ip has been blocked by youtube, thus i can't download the data by following the repo.
```
***************
* Download Starts *
***************
ERROR: [youtube] FkP2yE--B-Y: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
ERROR: [youtube] ucC-L4XAFAk: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
ERROR: [youtube] Al_ESaUdqWs: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
ERROR: [youtube] FwYClyBLIzE: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
ERROR: [youtube] WYmdFVLI_V4: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
```

So, Does the author have downloaded dataset and share please?
@VoxBlink2

**Comment by VoxBlink2** [comment]
Now the Youtube platform seems to conduct robot testing occasionally. We cannot provide the raw dataset because of the privacy security, but there is an alternative that you can sleep the process from time to time.
If you still get any questions, please contact us via email yuke.lin@dukekunshan.edu.cn with your purpose and information:).
